version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/astro"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      astro-dependencies:
        patterns:
          - "@astrojs/*"
          - "astro"
          - "@sentry/astro"
          - "@spotlightjs/astro"
          - "astro-*"
      react-dependencies:
        patterns:
          - "react"
          - "react-*"
          - "@radix-ui/react-*"
  - package-ecosystem: "npm"
    directory: "/worker-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      worker-dependencies:
        patterns:
          - "@cloudflare/*"
          - "wrangler"
          - "hono"
          - "@react-email/*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript*"
          - "eslint*"
          - "prettier*" 