version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/astro"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "npm"
      - "astro"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/worker-api"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    labels:
      - "dependencies"
      - "npm"
      - "worker-api"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "21:40"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
