@baseUrl = http://localhost:8787
@contentType = application/json

### Create a new comment
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "post_id": "123",
  "author_name": "Test User",
  "author_email": "test@example.com",
  "content": "This is a test comment"
}

### Create a reply comment
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "post_id": "123",
  "parentId": 1,
  "author_name": "Reply User",
  "author_email": "reply@example.com",
  "content": "This is a reply to the test comment"
}

### Get comments for a post
GET {{baseUrl}}/posts/123/comments?page=1&limit=20
Content-Type: {{contentType}}

### Get a specific comment
GET {{baseUrl}}/comments/1
Content-Type: {{contentType}}

### Like a comment
POST {{baseUrl}}/comments/1/like
Content-Type: {{contentType}}

### Unlike a comment
DELETE {{baseUrl}}/comments/1/like
Content-Type: {{contentType}} 