@baseUrl = http://localhost:8787
@contentType = application/json

### Invalid post ID
GET {{baseUrl}}/posts//comments
Content-Type: {{contentType}}

### Invalid comment ID
GET {{baseUrl}}/comments/abc
Content-Type: {{contentType}}

### Create comment with missing required fields
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "",
  "content": ""
}

### Create comment with invalid email
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "Test User",
  "authorEmail": "invalid-email",
  "content": "This is a test comment"
}

### Create reply to non-existent comment
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "parentId": 999999,
  "authorName": "Reply User",
  "content": "This is a reply to a non-existent comment"
}

### Like non-existent comment
POST {{baseUrl}}/comments/999999/like
Content-Type: {{contentType}}

### Unlike non-existent comment
DELETE {{baseUrl}}/comments/999999/like
Content-Type: {{contentType}} 