@baseUrl = http://localhost:8787
@contentType = application/json

### Get first page of comments
GET {{baseUrl}}/posts/123/comments?page=1&limit=5
Content-Type: {{contentType}}

### Get second page of comments
GET {{baseUrl}}/posts/123/comments?page=2&limit=5
Content-Type: {{contentType}}

### Get comments with custom page size
GET {{baseUrl}}/posts/123/comments?page=1&limit=10
Content-Type: {{contentType}}

### Get comments with invalid page number
GET {{baseUrl}}/posts/123/comments?page=0&limit=5
Content-Type: {{contentType}}

### Get comments with invalid page size
GET {{baseUrl}}/posts/123/comments?page=1&limit=0
Content-Type: {{contentType}}

### Get comments with large page size
GET {{baseUrl}}/posts/123/comments?page=1&limit=100
Content-Type: {{contentType}}

### Create multiple comments for testing pagination
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "User 1",
  "content": "Comment 1"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "User 2",
  "content": "Comment 2"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "User 3",
  "content": "Comment 3"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "User 4",
  "content": "Comment 4"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "authorName": "User 5",
  "content": "Comment 5"
}

### Create nested comments
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "parentId": 1,
  "authorName": "Reply User 1",
  "content": "Reply to Comment 1"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "parentId": 1,
  "authorName": "Reply User 2",
  "content": "Another reply to Comment 1"
}

###
POST {{baseUrl}}/comments
Content-Type: {{contentType}}

{
  "postId": "123",
  "parentId": 2,
  "authorName": "Reply User 3",
  "content": "Reply to Comment 2"
} 