name: deploy worker

on:
  push:
    branches: [ production, "feat/action/worker" ]

permissions:
  contents: read
  deployments: write

jobs:
  deploy-worker:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'worker-api'
          command: deploy ./src/index.ts --name ${{ secrets.CLOUDFLARE_WORKER_NAME }} --compatibility-date 2024-03-27
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}
          WEBSITE_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
          RESEND_AUDIENCE_ID: ${{ secrets.RESEND_AUDIENCE_ID }}
          RESEND_FROM: ${{ secrets.RESEND_FROM }}
